version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hellooo!"
workflows:
  build_and_test:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
